# Generated by Django 6.0.5 on 2026-05-28 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('damage', models.IntegerField(default=0)),
                ('cooldown', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'abilities',
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('base_health', models.IntegerField(default=100)),
                ('base_speed', models.IntegerField(default=10)),
            ],
            options={
                'db_table': 'characters',
            },
        ),
        migrations.CreateModel(
            name='Cosmetic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'cosmetics',
            },
        ),
        migrations.CreateModel(
            name='DailyQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=140)),
                ('reward_coins', models.IntegerField()),
            ],
            options={
                'db_table': 'daily_quest',
            },
        ),
        migrations.CreateModel(
            name='GameMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('max_players', models.IntegerField(default=8)),
                ('theme', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'game_maps',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_seconds', models.IntegerField()),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameplay.gamemap')),
            ],
            options={
                'db_table': 'matches',
            },
        ),
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=20, null=True)),
                ('level', models.IntegerField(default=1)),
                ('experience', models.IntegerField(default=0)),
                ('bread_coins', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'player_profile',
            },
        ),
        migrations.CreateModel(
            name='PlayerFriend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('became_friends_at', models.DateTimeField(auto_now_add=True)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friended_by', to='gameplay.playerprofile')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships', to='gameplay.playerprofile')),
            ],
            options={
                'db_table': 'player_friends',
            },
        ),
        migrations.CreateModel(
            name='PlayerCosmetic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('cosmetic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameplay.cosmetic')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cosmetics', to='gameplay.playerprofile')),
            ],
            options={
                'db_table': 'player_cosmetics',
            },
        ),
        migrations.CreateModel(
            name='MatchPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameplay.character')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameplay.match')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_performances', to='gameplay.playerprofile')),
            ],
            options={
                'db_table': 'match_players',
            },
        ),
        migrations.CreateModel(
            name='PlayerQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quests', to='gameplay.playerprofile')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameplay.dailyquest')),
            ],
            options={
                'db_table': 'player_quests',
            },
        ),
    ]
