# Generated by Django 6.0.5 on 2026-05-28 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('role', models.CharField(choices=[('hacker', 'Hacker/Debuffer'), ('tank', 'Tank/Control'), ('mage', 'Mage/Burst'), ('healer', 'Healer/DPS'), ('support', 'Support/Buffer')], default='hacker', max_length=20)),
                ('base_health', models.IntegerField(default=100)),
                ('base_damage', models.IntegerField(default=10)),
                ('base_stamina', models.IntegerField(default=10)),
                ('base_defense', models.IntegerField(default=5)),
                ('base_support', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'characters',
            },
        ),
        migrations.CreateModel(
            name='Cosmetic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'cosmetics',
            },
        ),
        migrations.CreateModel(
            name='DailyQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=140)),
                ('reward_coins', models.IntegerField()),
            ],
            options={
                'db_table': 'daily_quest',
            },
        ),
        migrations.CreateModel(
            name='GameMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('max_players', models.IntegerField(default=6)),
                ('theme', models.CharField(max_length=30)),
                ('lanes', models.IntegerField(default=3)),
            ],
            options={
                'db_table': 'game_maps',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=20)),
                ('correct_answer', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('required_level', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'question_categories',
            },
        ),
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ability_type', models.CharField(choices=[('attack', 'Attack'), ('defense', 'Defense'), ('buff', 'Buff'), ('debuff', 'Debuff'), ('heal', 'Heal')], default='attack', max_length=20)),
                ('power', models.IntegerField(default=0)),
                ('cooldown', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abilities', to='gameplay.character')),
            ],
            options={
                'db_table': 'abilities',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(default='Survival', max_length=30)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('lane_selection', 'Lane Selection'), ('in_progress', 'In Progress'), ('finished', 'Finished')], default='waiting', max_length=30)),
                ('winner_team', models.CharField(blank=True, choices=[('blue', 'Blue Team'), ('red', 'Red Team'), ('draw', 'Draw')], max_length=10, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameplay.gamemap')),
            ],
            options={
                'db_table': 'matches',
            },
        ),
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=20, null=True)),
                ('level', models.IntegerField(default=1)),
                ('experience', models.IntegerField(default=0)),
                ('bread_coins', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'player_profile',
            },
        ),
        migrations.CreateModel(
            name='PlayerFriend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('became_friends_at', models.DateTimeField(auto_now_add=True)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friended_by', to='gameplay.playerprofile')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships', to='gameplay.playerprofile')),
            ],
            options={
                'db_table': 'player_friends',
            },
        ),
        migrations.CreateModel(
            name='PlayerQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quests', to='gameplay.playerprofile')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameplay.dailyquest')),
            ],
            options={
                'db_table': 'player_quests',
            },
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='gameplay.question')),
            ],
            options={
                'db_table': 'answer_options',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='gameplay.questioncategory'),
        ),
        migrations.CreateModel(
            name='PlayerCosmetic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('cosmetic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameplay.cosmetic')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cosmetics', to='gameplay.playerprofile')),
            ],
            options={
                'db_table': 'player_cosmetics',
                'unique_together': {('profile', 'cosmetic')},
            },
        ),
        migrations.CreateModel(
            name='MatchPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(choices=[('blue', 'Blue Team'), ('red', 'Red Team')], max_length=10)),
                ('selected_lane', models.CharField(choices=[('top', 'Top Lane'), ('mid', 'Mid Lane'), ('bot', 'Bot Lane')], max_length=10)),
                ('remaining_health', models.IntegerField(default=100)),
                ('score', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('wrong_answers', models.IntegerField(default=0)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameplay.character')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='gameplay.match')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_performances', to='gameplay.playerprofile')),
            ],
            options={
                'db_table': 'match_players',
                'unique_together': {('match', 'profile')},
            },
        ),
    ]
